### ISSUE TITLE
Is this a good idea?

### ISSUE THREAD

**Issue by morficus** [awesome-testing-org/portfolio#2]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in ultrices enim, rhoncus aliquam nibh. Donec vel tempor quam, ac euismod metus. Integer accumsan dolor nisl, ac dapibus nulla scelerisque at. Ut tincidunt imperdiet nunc, sit amet sollicitudin erat commodo ut. Aliquam blandit hendrerit eros, vitae ullamcorper tellus pretium nec. Nulla in magna porttitor, tincidunt neque id, molestie dolor. Nulla facilisi. Pellentesque ullamcorper dolor eu mauris mollis, porttitor fringilla tortor congue. Phasellus finibus velit enim, a pulvinar lectus blandit eu.

**Comment by morficus** [comment]
comments comments, so many comments

**Comment by morficus** [comment]
here are the stories (or tasks... w/e you want to call them):

* [ ] https://github.com/awesome-testing-org/sample-repo-2/issues/1
* [ ] https://github.com/awesome-testing-org/sample-repo-1/issues/2
* [ ] https://github.com/awesome-testing-org/sample-repo-1/issues/3

**Comment by morficus** [comment]
I do not recommend linking/tracking like this because is gives no insight in to what is going in on the "lower level" issues

**Comment by DarrylD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [this is some much more fluid](https://trello.com/c/c79ZHPpo/1-this-is-some-much-more-fluid)

**Comment by morficus** [comment]
testing testing testing
